set_languages("cxx20")
set_arch("x64")
add_rules("mode.debug", "mode.release")
add_requires("spdlog", "nlohmann_json")

add_defines("UNICODE")

target("cet_mod_manager")
    set_kind("shared")
    set_filename("cet_mod_manager.asi")
    add_packages("spdlog", "nlohmann_json")
    add_files("src/**.cpp")
    add_headerfiles("src/**.h")
    set_pcxxheader("src/pch.h")
    add_includedirs("src/", "src/embeds/")
    on_package(function (target)
        import("build")
        build.Package(target)
    end)
    on_install(function ()
        import("build")
        build.Install()
    end)

    before_build(function (target)
        import("build")
        build.UpdateVersion()
        build.GenerateEmbeds()
    end)

    after_clean(function ()
        import("build")
        build.Clean()
    end)

option("installpath")
    set_showmenu(true)
    set_description("Set the path to Cyberpunk 2077 root directory.", "e.g.", format("\t-xmake f --installpath=%s", [["C:\Program Files (x86)\Steam\steamapps\common\Cyberpunk 2077"]]))

task("run")
    on_run(function ()
        import("core.project.config")
        config.load()
        local install_path = config.get("installpath")
        print("Launching Cyberpunk 2077 ...")
        os.cd(path.join(install_path, "bin", "x64"))
        os.run("Cyberpunk2077.exe")
    end)
    set_menu { usage = "xmake run", description = "Launch Cyberpunk 2077"}

task("embed")
    on_run(function ()
        import("build")
        build.GenerateEmbeds()
    end)
    set_menu { usage = "xmake embed", description = "Generate embed files"}