set_languages("cxx20")
set_arch("x64")
add_rules("mode.debug", "mode.release")
add_requires("spdlog")

add_defines("UNICODE")

target("cet_mod_manager")
    set_kind("shared")
    set_filename("cet_mod_manager.asi")
    set_pcxxheader("src/pch.h")
    add_packages("spdlog")
    add_files("src/**.cpp")
    add_headerfiles("src/**.h")
    add_includedirs("src/")
    on_package(function (target)
        os.mkdir("package/bin/x64/plugins/cyber_engine_tweaks/mods/cet_mod_manager")
		os.cp("*.lua", "package/bin/x64/plugins/cyber_engine_tweaks/mods/cet_mod_manager")
		os.cp("LICENSE", "package/bin/x64/plugins/cyber_engine_tweaks/mods/cet_mod_manager")
        os.cp("Third_Party_LICENSES", "package/bin/x64/plugins/cyber_engine_tweaks/mods/cet_mod_manager")
        os.cp("dofiles/", "package/bin/x64/plugins/cyber_engine_tweaks/mods/cet_mod_manager")
        os.cp("i18n/", "package/bin/x64/plugins/cyber_engine_tweaks/mods/cet_mod_manager")
        os.cp("lang/", "package/bin/x64/plugins/cyber_engine_tweaks/mods/cet_mod_manager")
        os.cp("scripts/", "package/bin/x64/plugins/cyber_engine_tweaks/mods/cet_mod_manager")
		os.rm("package/bin/x64/plugins/cyber_engine_tweaks/mods/cet_mod_manager/xmake.lua")
		os.cp(target:targetfile(), "package/bin/x64/plugins/")
    end)
    on_install(function (target)
        os.cp(target:targetfile(), "C:/Program Files (x86)/Steam/steamapps/common/Cyberpunk 2077/bin/x64/plugins") -- My game path
    end)
